// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA00uY25A-I403YwiKY0-3Z1ddRCbOZaFw',
    appId: '1:153918463038:web:d0728664556a53dffc856f',
    messagingSenderId: '153918463038',
    projectId: 'sast-63e2b',
    authDomain: 'sast-63e2b.firebaseapp.com',
    storageBucket: 'sast-63e2b.firebasestorage.app',
    measurementId: 'G-6LNVWB70KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4uLD9Ek-nwEmmqhQagJgCA1CD41QAL3g',
    appId: '1:153918463038:android:adf30e70a74e3eacfc856f',
    messagingSenderId: '153918463038',
    projectId: 'sast-63e2b',
    storageBucket: 'sast-63e2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIHp4_Zfl2N67J51ouLaJq1mLe9bRyA4E',
    appId: '1:153918463038:ios:c9346e80af6168c2fc856f',
    messagingSenderId: '153918463038',
    projectId: 'sast-63e2b',
    storageBucket: 'sast-63e2b.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIHp4_Zfl2N67J51ouLaJq1mLe9bRyA4E',
    appId: '1:153918463038:ios:c9346e80af6168c2fc856f',
    messagingSenderId: '153918463038',
    projectId: 'sast-63e2b',
    storageBucket: 'sast-63e2b.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA00uY25A-I403YwiKY0-3Z1ddRCbOZaFw',
    appId: '1:153918463038:web:9ee4b8a5aed305b3fc856f',
    messagingSenderId: '153918463038',
    projectId: 'sast-63e2b',
    authDomain: 'sast-63e2b.firebaseapp.com',
    storageBucket: 'sast-63e2b.firebasestorage.app',
    measurementId: 'G-3YS19K6SSM',
  );

}